-- MySQL Script generated by MySQL Workbench
-- Fri Aug 23 11:36:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `IdPerfil` INT NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `DataCriacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdPerfil`));


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `IdUsuario` INT NOT NULL,
  `IdPerfil` INT NOT NULL,
  `Usuario` VARCHAR(16) NOT NULL,
  `Senha` VARCHAR(32) NOT NULL,
  `Email` VARCHAR(255) NULL,
  `DataCriacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdUsuario`),
  INDEX `FK_Perfil_IdPerfil_idx` (`IdPerfil` ASC) VISIBLE,
  CONSTRAINT `FK_Perfil_IdPerfil`
    FOREIGN KEY (`IdPerfil`)
    REFERENCES `mydb`.`perfil` (`IdPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`unidadetempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidadetempo` (
  `IdUnidadeTempo` INT NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `DataCriacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdUnidadeTempo`));


-- -----------------------------------------------------
-- Table `mydb`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projeto` (
  `IdProjeto` INT NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `PrazoPrevistoMinimo` INT NULL DEFAULT 0,
  `PrazoPrevistoMaximo` INT NULL,
  `IdUnidadeTempo` INT NULL,
  `ValorPrevisto` REAL NULL,
  `DataCriacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdProjeto`),
  INDEX `FK_Unidade_Tempo_IdUnidadeTempo_idx` (`IdUnidadeTempo` ASC) VISIBLE,
  CONSTRAINT `FK_Unidade_Tempo_IdUnidadeTempo`
    FOREIGN KEY (`IdUnidadeTempo`)
    REFERENCES `mydb`.`unidadetempo` (`IdUnidadeTempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato` (
  `IdContrato` INT NOT NULL,
  `IdProjeto` INT NOT NULL,
  `IdContratante` INT NOT NULL,
  `IdContratado` INT NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `DataCriacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `DataEncerramento` TIMESTAMP NULL,
  `ValorContratado` REAL NULL,
  PRIMARY KEY (`IdContrato`),
  INDEX `FK_Projeto_IdProjeto_idx` (`IdProjeto` ASC) VISIBLE,
  INDEX `FK_Usuario_IdContratante_idx` (`IdContratante` ASC) VISIBLE,
  INDEX `FK_Usuario_IdContratado_idx` (`IdContratado` ASC) VISIBLE,
  CONSTRAINT `FK_Projeto_IdProjeto`
    FOREIGN KEY (`IdProjeto`)
    REFERENCES `mydb`.`projeto` (`IdProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Usuario_IdContratante`
    FOREIGN KEY (`IdContratante`)
    REFERENCES `mydb`.`usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Usuario_IdContratado`
    FOREIGN KEY (`IdContratado`)
    REFERENCES `mydb`.`usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarefa` (
  `IdTarefa` INT NOT NULL,
  `IdProjeto` INT NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  `DataInicio` TIMESTAMP NULL,
  `DataEncerramento` TIMESTAMP NULL,
  `DataCriacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `PrazoPrevisto` INT NULL,
  `IdUnidadeTempo` INT NULL,
  PRIMARY KEY (`IdTarefa`),
  INDEX `FK_Projeto_IdProjeto_idx` (`IdProjeto` ASC) VISIBLE,
  INDEX `FK_UnidadeTempo_IdUnidadeTempo_idx` (`IdUnidadeTempo` ASC) VISIBLE,
  CONSTRAINT `FK_Projeto_IdProjeto`
    FOREIGN KEY (`IdProjeto`)
    REFERENCES `mydb`.`projeto` (`IdProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UnidadeTempo_IdUnidadeTempo`
    FOREIGN KEY (`IdUnidadeTempo`)
    REFERENCES `mydb`.`unidadetempo` (`IdUnidadeTempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
